// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fileformat.proto

package OSMPBF

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import bytes "bytes"

import strings "strings"
import reflect "reflect"

import io "io"
import github_com_gogo_protobuf_proto "github.com/gogo/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Blob struct {
	Raw     []byte `protobuf:"bytes,1,opt,name=raw" json:"raw"`
	RawSize int32  `protobuf:"varint,2,opt,name=raw_size,json=rawSize" json:"raw_size"`
	// Possible compressed versions of the data.
	ZlibData []byte `protobuf:"bytes,3,opt,name=zlib_data,json=zlibData" json:"zlib_data"`
	// PROPOSED feature for LZMA compressed data. SUPPORT IS NOT REQUIRED.
	LzmaData []byte `protobuf:"bytes,4,opt,name=lzma_data,json=lzmaData" json:"lzma_data"`
	// Formerly used for bzip2 compressed data. Depreciated in 2010.
	OBSOLETEBzip2Data []byte `protobuf:"bytes,5,opt,name=OBSOLETE_bzip2_data,json=OBSOLETEBzip2Data" json:"OBSOLETE_bzip2_data"` // Deprecated: Do not use.
}

func (m *Blob) Reset()      { *m = Blob{} }
func (*Blob) ProtoMessage() {}
func (*Blob) Descriptor() ([]byte, []int) {
	return fileDescriptor_fileformat_1e2c4341e5bdecc6, []int{0}
}
func (m *Blob) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Blob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Blob.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Blob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blob.Merge(dst, src)
}
func (m *Blob) XXX_Size() int {
	return m.Size()
}
func (m *Blob) XXX_DiscardUnknown() {
	xxx_messageInfo_Blob.DiscardUnknown(m)
}

var xxx_messageInfo_Blob proto.InternalMessageInfo

func (m *Blob) GetRaw() []byte {
	if m != nil {
		return m.Raw
	}
	return nil
}

func (m *Blob) GetRawSize() int32 {
	if m != nil {
		return m.RawSize
	}
	return 0
}

func (m *Blob) GetZlibData() []byte {
	if m != nil {
		return m.ZlibData
	}
	return nil
}

func (m *Blob) GetLzmaData() []byte {
	if m != nil {
		return m.LzmaData
	}
	return nil
}

// Deprecated: Do not use.
func (m *Blob) GetOBSOLETEBzip2Data() []byte {
	if m != nil {
		return m.OBSOLETEBzip2Data
	}
	return nil
}

type BlobHeader struct {
	Type      string `protobuf:"bytes,1,req,name=type" json:"type"`
	Indexdata []byte `protobuf:"bytes,2,opt,name=indexdata" json:"indexdata"`
	Datasize  int32  `protobuf:"varint,3,req,name=datasize" json:"datasize"`
}

func (m *BlobHeader) Reset()      { *m = BlobHeader{} }
func (*BlobHeader) ProtoMessage() {}
func (*BlobHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_fileformat_1e2c4341e5bdecc6, []int{1}
}
func (m *BlobHeader) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BlobHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BlobHeader.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *BlobHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlobHeader.Merge(dst, src)
}
func (m *BlobHeader) XXX_Size() int {
	return m.Size()
}
func (m *BlobHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlobHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlobHeader proto.InternalMessageInfo

func (m *BlobHeader) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *BlobHeader) GetIndexdata() []byte {
	if m != nil {
		return m.Indexdata
	}
	return nil
}

func (m *BlobHeader) GetDatasize() int32 {
	if m != nil {
		return m.Datasize
	}
	return 0
}

func init() {
	proto.RegisterType((*Blob)(nil), "OSMPBF.Blob")
	proto.RegisterType((*BlobHeader)(nil), "OSMPBF.BlobHeader")
}
func (this *Blob) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Blob)
	if !ok {
		that2, ok := that.(Blob)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.Raw, that1.Raw) {
		return false
	}
	if this.RawSize != that1.RawSize {
		return false
	}
	if !bytes.Equal(this.ZlibData, that1.ZlibData) {
		return false
	}
	if !bytes.Equal(this.LzmaData, that1.LzmaData) {
		return false
	}
	if !bytes.Equal(this.OBSOLETEBzip2Data, that1.OBSOLETEBzip2Data) {
		return false
	}
	return true
}
func (this *BlobHeader) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*BlobHeader)
	if !ok {
		that2, ok := that.(BlobHeader)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Type != that1.Type {
		return false
	}
	if !bytes.Equal(this.Indexdata, that1.Indexdata) {
		return false
	}
	if this.Datasize != that1.Datasize {
		return false
	}
	return true
}
func (this *Blob) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&OSMPBF.Blob{")
	s = append(s, "Raw: "+fmt.Sprintf("%#v", this.Raw)+",\n")
	s = append(s, "RawSize: "+fmt.Sprintf("%#v", this.RawSize)+",\n")
	s = append(s, "ZlibData: "+fmt.Sprintf("%#v", this.ZlibData)+",\n")
	s = append(s, "LzmaData: "+fmt.Sprintf("%#v", this.LzmaData)+",\n")
	s = append(s, "OBSOLETEBzip2Data: "+fmt.Sprintf("%#v", this.OBSOLETEBzip2Data)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *BlobHeader) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&OSMPBF.BlobHeader{")
	s = append(s, "Type: "+fmt.Sprintf("%#v", this.Type)+",\n")
	s = append(s, "Indexdata: "+fmt.Sprintf("%#v", this.Indexdata)+",\n")
	s = append(s, "Datasize: "+fmt.Sprintf("%#v", this.Datasize)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringFileformat(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *Blob) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Blob) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Raw != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintFileformat(dAtA, i, uint64(len(m.Raw)))
		i += copy(dAtA[i:], m.Raw)
	}
	dAtA[i] = 0x10
	i++
	i = encodeVarintFileformat(dAtA, i, uint64(m.RawSize))
	if m.ZlibData != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintFileformat(dAtA, i, uint64(len(m.ZlibData)))
		i += copy(dAtA[i:], m.ZlibData)
	}
	if m.LzmaData != nil {
		dAtA[i] = 0x22
		i++
		i = encodeVarintFileformat(dAtA, i, uint64(len(m.LzmaData)))
		i += copy(dAtA[i:], m.LzmaData)
	}
	if m.OBSOLETEBzip2Data != nil {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintFileformat(dAtA, i, uint64(len(m.OBSOLETEBzip2Data)))
		i += copy(dAtA[i:], m.OBSOLETEBzip2Data)
	}
	return i, nil
}

func (m *BlobHeader) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BlobHeader) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintFileformat(dAtA, i, uint64(len(m.Type)))
	i += copy(dAtA[i:], m.Type)
	if m.Indexdata != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintFileformat(dAtA, i, uint64(len(m.Indexdata)))
		i += copy(dAtA[i:], m.Indexdata)
	}
	dAtA[i] = 0x18
	i++
	i = encodeVarintFileformat(dAtA, i, uint64(m.Datasize))
	return i, nil
}

func encodeVarintFileformat(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Blob) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Raw != nil {
		l = len(m.Raw)
		n += 1 + l + sovFileformat(uint64(l))
	}
	n += 1 + sovFileformat(uint64(m.RawSize))
	if m.ZlibData != nil {
		l = len(m.ZlibData)
		n += 1 + l + sovFileformat(uint64(l))
	}
	if m.LzmaData != nil {
		l = len(m.LzmaData)
		n += 1 + l + sovFileformat(uint64(l))
	}
	if m.OBSOLETEBzip2Data != nil {
		l = len(m.OBSOLETEBzip2Data)
		n += 1 + l + sovFileformat(uint64(l))
	}
	return n
}

func (m *BlobHeader) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Type)
	n += 1 + l + sovFileformat(uint64(l))
	if m.Indexdata != nil {
		l = len(m.Indexdata)
		n += 1 + l + sovFileformat(uint64(l))
	}
	n += 1 + sovFileformat(uint64(m.Datasize))
	return n
}

func sovFileformat(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozFileformat(x uint64) (n int) {
	return sovFileformat(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Blob) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Blob{`,
		`Raw:` + fmt.Sprintf("%v", this.Raw) + `,`,
		`RawSize:` + fmt.Sprintf("%v", this.RawSize) + `,`,
		`ZlibData:` + fmt.Sprintf("%v", this.ZlibData) + `,`,
		`LzmaData:` + fmt.Sprintf("%v", this.LzmaData) + `,`,
		`OBSOLETEBzip2Data:` + fmt.Sprintf("%v", this.OBSOLETEBzip2Data) + `,`,
		`}`,
	}, "")
	return s
}
func (this *BlobHeader) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&BlobHeader{`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`Indexdata:` + fmt.Sprintf("%v", this.Indexdata) + `,`,
		`Datasize:` + fmt.Sprintf("%v", this.Datasize) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringFileformat(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Blob) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFileformat
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Blob: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Blob: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Raw", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileformat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthFileformat
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Raw = append(m.Raw[:0], dAtA[iNdEx:postIndex]...)
			if m.Raw == nil {
				m.Raw = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawSize", wireType)
			}
			m.RawSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileformat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RawSize |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZlibData", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileformat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthFileformat
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ZlibData = append(m.ZlibData[:0], dAtA[iNdEx:postIndex]...)
			if m.ZlibData == nil {
				m.ZlibData = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LzmaData", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileformat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthFileformat
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LzmaData = append(m.LzmaData[:0], dAtA[iNdEx:postIndex]...)
			if m.LzmaData == nil {
				m.LzmaData = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OBSOLETEBzip2Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileformat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthFileformat
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OBSOLETEBzip2Data = append(m.OBSOLETEBzip2Data[:0], dAtA[iNdEx:postIndex]...)
			if m.OBSOLETEBzip2Data == nil {
				m.OBSOLETEBzip2Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFileformat(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFileformat
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BlobHeader) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFileformat
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BlobHeader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BlobHeader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileformat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFileformat
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Indexdata", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileformat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthFileformat
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Indexdata = append(m.Indexdata[:0], dAtA[iNdEx:postIndex]...)
			if m.Indexdata == nil {
				m.Indexdata = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Datasize", wireType)
			}
			m.Datasize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileformat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Datasize |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipFileformat(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFileformat
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("type")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("datasize")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFileformat(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFileformat
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFileformat
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFileformat
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthFileformat
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowFileformat
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipFileformat(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthFileformat = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFileformat   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("fileformat.proto", fileDescriptor_fileformat_1e2c4341e5bdecc6) }

var fileDescriptor_fileformat_1e2c4341e5bdecc6 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xb1, 0x4e, 0x02, 0x31,
	0x18, 0xc7, 0xfb, 0xdd, 0x1d, 0x08, 0x5f, 0x34, 0xd1, 0x9a, 0x98, 0x9b, 0x3e, 0x4e, 0x26, 0x26,
	0x06, 0x07, 0x1f, 0xa0, 0x11, 0xc3, 0xa0, 0xc1, 0x80, 0x3b, 0xe9, 0x49, 0x49, 0x9a, 0x1c, 0x1c,
	0x29, 0x97, 0x20, 0x37, 0xf9, 0x08, 0x3e, 0x86, 0x2f, 0xe1, 0xce, 0xc8, 0xc8, 0x64, 0xa4, 0x2c,
	0x8e, 0x3c, 0x82, 0xe9, 0x81, 0xc8, 0xd4, 0xe4, 0xd7, 0xdf, 0xbf, 0xfd, 0xff, 0xf1, 0x7c, 0xa8,
	0x13, 0x35, 0x4c, 0xcd, 0x48, 0x66, 0xcd, 0x89, 0x49, 0xb3, 0x94, 0x97, 0x3b, 0xbd, 0xc7, 0x27,
	0x71, 0x5f, 0xff, 0x04, 0x0c, 0x44, 0x92, 0xc6, 0xfc, 0x0a, 0x7d, 0x23, 0x67, 0x21, 0x44, 0xd0,
	0x38, 0x15, 0xc1, 0xe2, 0xab, 0xc6, 0xba, 0x0e, 0xf0, 0x1a, 0x56, 0x8c, 0x9c, 0xf5, 0xa7, 0x3a,
	0x57, 0xa1, 0x17, 0x41, 0xa3, 0xb4, 0xbf, 0x3c, 0x31, 0x72, 0xd6, 0xd3, 0xb9, 0xe2, 0xd7, 0x58,
	0xcd, 0x13, 0x1d, 0xf7, 0x07, 0x32, 0x93, 0xa1, 0x7f, 0x14, 0xaf, 0x38, 0x7c, 0x27, 0x33, 0xe9,
	0x94, 0x24, 0x1f, 0xc9, 0x9d, 0x12, 0x1c, 0x2b, 0x0e, 0x17, 0xca, 0x2d, 0x5e, 0x76, 0x44, 0xaf,
	0xf3, 0xd0, 0x7a, 0x6e, 0xf5, 0xe3, 0x5c, 0x4f, 0x6e, 0x76, 0x72, 0xa9, 0x90, 0xcb, 0x4e, 0x0e,
	0xa1, 0x7b, 0xf1, 0xa7, 0x08, 0x67, 0xb8, 0x5c, 0x3d, 0x41, 0x74, 0xf5, 0xdb, 0x4a, 0x0e, 0x94,
	0xe1, 0x21, 0x06, 0xd9, 0x7c, 0xa2, 0x42, 0x88, 0xbc, 0x46, 0x75, 0xff, 0x47, 0x41, 0x78, 0x1d,
	0xab, 0x7a, 0x3c, 0x50, 0xaf, 0xc5, 0xab, 0xde, 0x51, 0x85, 0x7f, 0xcc, 0x23, 0xac, 0xb8, 0xb3,
	0x98, 0xea, 0x47, 0xde, 0x61, 0xea, 0x81, 0x8a, 0xd6, 0x72, 0x4d, 0x6c, 0xb5, 0x26, 0xb6, 0x5d,
	0x13, 0xbc, 0x59, 0x82, 0x0f, 0x4b, 0xb0, 0xb0, 0x04, 0x4b, 0x4b, 0xf0, 0x6d, 0x09, 0x7e, 0x2c,
	0xb1, 0xad, 0x25, 0x78, 0xdf, 0x10, 0x5b, 0x6e, 0x88, 0xad, 0x36, 0xc4, 0xf0, 0xec, 0xc5, 0xa4,
	0xd3, 0x78, 0xde, 0x8c, 0xf5, 0x58, 0x9a, 0x79, 0xdb, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x0d,
	0x18, 0x05, 0xdb, 0x8f, 0x01, 0x00, 0x00,
}
